/* tslint:disable */
/* eslint-disable */
/**
 * 崩坏晓店
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Categories
 */
export interface Categories {
    /**
     * 
     * @type {number}
     * @memberof Categories
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Categories
     */
    'categoryName'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Categories
     */
    'isStatus'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof Categories
     */
    'isDelete'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof Categories
     */
    'createTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Categories
     */
    'updateTime'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Categories
     */
    'status'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Categories
     */
    'delete'?: boolean | null;
}

