/* tslint:disable */
/* eslint-disable */
/**
 * 崩坏晓店
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Orders
 */
export interface Orders {
    /**
     * 
     * @type {number}
     * @memberof Orders
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Orders
     */
    'orderNumber'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Orders
     */
    'usersId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Orders
     */
    'teatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Orders
     */
    'deliveryStatus'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Orders
     */
    'totalAmount'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Orders
     */
    'isDelete'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof Orders
     */
    'createTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Orders
     */
    'updateTime'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Orders
     */
    'delete'?: boolean | null;
}

