/* tslint:disable */
/* eslint-disable */
/**
 * 崩坏晓店
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Orderdetails
 */
export interface Orderdetails {
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'orderId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'productId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'addressesId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'quantity'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'unitPrice'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'price'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'actualPayment'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Orderdetails
     */
    'preferential'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Orderdetails
     */
    'createTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Orderdetails
     */
    'updateTime'?: string | null;
}

