/* tslint:disable */
/* eslint-disable */
/**
 * 崩坏晓店
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SysMenu
 */
export interface SysMenu {
    /**
     * 
     * @type {number}
     * @memberof SysMenu
     */
    'id'?: number | null;
    /**
     * 菜单名
     * @type {string}
     * @memberof SysMenu
     */
    'menuName'?: string | null;
    /**
     * 菜单状态（0正常 1停用）
     * @type {boolean}
     * @memberof SysMenu
     */
    'status'?: boolean | null;
    /**
     * 菜单状态（0未删除 1删除）
     * @type {boolean}
     * @memberof SysMenu
     */
    'isDelete'?: boolean | null;
    /**
     * 权限
     * @type {string}
     * @memberof SysMenu
     */
    'perms'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SysMenu
     */
    'createTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SysMenu
     */
    'updateTime'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SysMenu
     */
    'delete'?: boolean | null;
}

