/* tslint:disable */
/* eslint-disable */
/**
 * 崩坏晓店
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Users
 */
export interface Users {
    /**
     * 
     * @type {number}
     * @memberof Users
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'password'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'is_status'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Users
     */
    'is_delete'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'create_time'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Users
     */
    'update_time'?: string | null;
}

